---        
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: copy war file into tomcat server
      copy:
        src: /var/lib/jenkins/workspace/Declarative_pipeline/target/*.war
        dest: /opt/tomcat-8.5.70/webapps/
      
